### ISSUE TITLE
Token関連のエンドポイントが欲しい

### ISSUE THREAD

**Issue by Yourein** [fung-hackathon/flyme-backend#66]
# これはなに

Token発行時に有効時間が通知されていない(expired_inが通知されていない)ので、Tokenが有効であるかを判定するエンドポイントが欲しい。もしくは発行時にexpired_inを一緒に入れてほしい。

また、失効したTokenを渡すことでtokenをregenerateするかreactivateしてほしい。(これはセキュリティの面から微妙そうという話もある)

**Comment by TadaTeruki** [comment]
#68 
> Tokenが有効であるかを判定するエンドポイントが欲しい

こちらはできそう。実装したので試してほしい

> 失効したTokenを渡すことでtokenをregenerateするかreactivateしてほしい

こちらは正直厳しそう。github.com/golang-jwt/jwt/v4 だと有効期限の切れたトークンからClaimを読み出すことができなくなっていて、過去のトークンに保持されている情報を使い回せない (できなくしているんじゃないかな、要深堀り)。jugesukeの言ったようにRefreshトークンとAccessトークンで分けて発行するようにするか、ユーザーIDとパスワードをなんらか加工してローカルで保存してもらって再ログインしてもらうしかない気がしているんだけど、どうだろう

**Comment by Yourein** [comment]
Regenerateについては厳しそうならやらなくて大丈夫(自分もexpired tokenを判定するのキツくない？と思っていたので)

ちょっと気持ち悪いけどuserLoginの部分を使い回すことにする

**Comment by TadaTeruki** [comment]
となると、今の時点の実装で大丈夫かもね
@jugesuke にレビューお願いします

**Comment by jugesuke** [comment]
Reviewしてマージしました
