### ISSUE TITLE
Tokenの持続時間がおかしい (短い)

### ISSUE THREAD

**Issue by Yourein** [fung-hackathon/flyme-backend#67]
> [1:59 AM] jugesuke: 24hで失効です、たしか
> [2:00 AM] Yourein: ん、明らかに24h未満で失効しています

本来24h持続するはずのtokenが10分くらいでinvalidになる。
個人的にはrender上のコンテナがsleepした際に失効しているような気がしている。  
(もしかしたら普通にフロント/バック側でまずい実装をしている可能性もある)

このissueのために #66 があるといいなぁという気持ちになった。

**Comment by jugesuke** [comment]
署名キーをサーバ起動時に毎回生成しているのが原因かと

render (Hosting Service) がスリープした後、再起動する際に署名キーがリセットされている

**Comment by jugesuke** [comment]
署名キーをサーバ起動時に毎回生成しているのが原因かと

render (Hosting Service) がスリープした後、再起動する際に署名キーがリセットされている

**Comment by Yourein** [comment]
https://github.com/fung-hackathon/flyme-backend/issues/66 の付属で生えたissueなので、renderが原因となっているならば対応不要。一旦このissueはCloseする。

@jugesuke もし認証サービスを現在のものから変えるなら、それは別のIssueやMilestoneを建ててほしい。
